###############################################################
# This config file runs bigchaindb:0.10.1 as a k8s Deployment #
# and it connects to the mongodb backend running as a         #
# separate pod                                                #
###############################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdb-instance-0-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bdb-instance-0-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bigchaindb
        image: bigchaindb/bigchaindb:0.10.2
        imagePullPolicy: IfNotPresent
        args:
        - start
        env:
        - name: BIGCHAINDB_DATABASE_HOST
          value: mdb-instance-0
        - name: BIGCHAINDB_DATABASE_PORT
          value: "27017"
        - name: BIGCHAINDB_DATABASE_REPLICASET
          value: bigchain-rs
        - name: BIGCHAINDB_DATABASE_BACKEND
          value: mongodb
        - name: BIGCHAINDB_DATABASE_NAME
          value: bigchain
        - name: BIGCHAINDB_SERVER_BIND
          value: 0.0.0.0:9984
        - name: BIGCHAINDB_WSSERVER_HOST
          value: 0.0.0.0
        - name: BIGCHAINDB_WSSERVER_PORT
          value: "9985"
        - name: BIGCHAINDB_KEYPAIR_PUBLIC
          value: "<public key here>"
        - name: BIGCHAINDB_KEYPAIR_PRIVATE
          value: "<private key here>"
        - name: BIGCHAINDB_BACKLOG_REASSIGN_DELAY
          value: "120"
        - name: BIGCHAINDB_DATABASE_MAXTRIES
          value: "3"
        - name: BIGCHAINDB_DATABASE_CONNECTION_TIMEOUT
          value: "120"
        - name: BIGCHAINDB_LOG_LEVEL_CONSOLE
          value: debug
        - name: BIGCHAINDB_DATABASE_CA_CERT
          value: /etc/bigchaindb/ssl/ca.pem
        - name: BIGCHAINDB_DATABASE_CRLFILE
          value: /etc/bigchaindb/ssl/crlfile
        - name: BIGCHAINDB_DATABASE_CERTFILE
          value: /etc/bigchaindb/ssl/bdb-instance.pem
        - name: BIGCHAINDB_DATABASE_KEYFILE
          value: /etc/bigchaindb/ssl/bdb-instance.key
        - name: BIGCHAINDB_DATABASE_KEYFILE_PASSPHRASE
          value: /etc/bigchaindb/ssl/bdb-keyfile-passphrase
        - name: BIGCHAINDB_DATABASE_LOGIN
          value: /etc/bigchaindb/ssl/bdb-user
        # The following env var is not required for the bootstrap/first node
        #- name: BIGCHAINDB_KEYRING
        #  value: ""
        ports:
        - containerPort: 9984
          hostPort: 9984
          name: bdb-port
          protocol: TCP
        - containerPort: 9985
          hostPort: 9985
          name: bdb-ws-port
          protocol: TCP
        volumeMounts:
        - name: bdb-certs
          mountPath: /etc/bigchaindb/ssl/
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
      volumes:
      - name: bdb-certs
        secret:
          secretName: bdb-certs
          defaultMode: 0400
